# Generated by Django 5.1.4 on 2024-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
